### ISSUE TITLE
Is this the SDK for ezbuy.com?

### ISSUE THREAD

**Issue by lackdaz** [ezbuy/wrapper#6]
Hi, I'm a developer looking to integrate our purchases from ezbuy into an google sheets.

We use the e-commerce platform a lot for our prototyping needs and its become quite a pain to search the purchase history for repeat purchases. To complicate things further, you've wrapped long purchase orders to a maximum of 3 shown, requiring users to click to show more.

While I understand that developing a search field might be asking for too much, I'm hoping to develop an application to just shadow our purchases to a duplicate local database for easy data manipulation as a stop-gap.

Any way I could contact you guys about a way to develop a solution for this?
I can be reached seth (at) madebyif.com

**Comment by scbizu** [comment]
Hi, lackdaz. Since this is an off-topic issue, I'll close it for now, but I will forward your ideas to our product  managers. They may contact you in few days or not , it depends on them. 

Thanks for your feedback , happy ezbuy XD
